version: '3'
services:
    cache-api: 
        build: .
        ports:
            - "5000:8080"
        environment:
            - APP_ENV=development 
        restart: always
        volumes: 
            - .:/app